[package]
name = "deepcube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-iterator = "0.7.0"
rand = "0.8.4"
ansi_term = "0.12.1"
rayon = "1.5.1"
ux = "0.1.3"